import React, { useState } from 'react';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Menu from './Menu';
import ControleEditora from '../classes/controle/ControleEditora';

const LivroDados: React.FC = () => {
  const controleEditora = new ControleEditora();
  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const incluirLivro = async (livro: Livro) => {
    const response = await fetch(baseURL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(livro),
    });
    return response.ok;
  };

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = async (event: React.FormEvent) => {
    event.preventDefault();
    const livro = new Livro(0, codEditora, titulo, resumo, autores.split('\n'));
    const incluiu = await incluirLivro(livro);
    if (incluiu) {
      navigate('/LivroLista');
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Dados do Livro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}>
        <h1 className={styles.title}>Dados do Livro</h1>
        {/* Formulario para entrada de dados */}
      </main>
    </div>
  );
};

export default LivroDados